version: "3.9"
services:
  backend:
    container_name: ai-streamlit
    build: ./streamlit_app/
    ports:
      - "8000:8501"
    restart: always
    networks:
      - ai_network
#    env_file: .env

  instagram_crawler:
    container_name: instagram_crawler
    build: ./Crawler_Task/
    volumes:
      - './Crawler_Task/logs:/usr/src/app/logs'
    restart: always
    networks:
      - ai_network
#    env_file: .env

  frontend:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: always
    networks:
      - ai_network

  mongo:
    container_name: streamlit_mongodb
    image: mongo
    ports: 
      - 27017:27017
#    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: instagram_data 
    restart: always
    volumes:
      - './data:/data/db'
      - './Crawler_Task/dump:/dump'
    networks:
      - ai_network
      
networks:
  ai_network:
